### ISSUE TITLE
Cannot find "textAlign" in this widget

### ISSUE THREAD

**Issue by mohammednabil95** [iampopal/flutter_locales#2]
Is there textAlign is available in this widget or any sort of similar properties in this library?

**Comment by yasin1376** [comment]
You can use like this:

Text("${Locales.string(context, 'your_key')}", textAlign: TextAlign.center);

**Comment by mohammednabil95** [comment]
@yasin1376 What is "your_key" ? Is this a "LocaleNotifier.of(context)!.change('en');" ?

**Comment by yasin1376** [comment]
@mohammednabil95 No, this is the key from your JSON file.

**Comment by iampopal** [comment]
In New version LocaleText also have support for `textAlign` poroprty
