### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by aakarapetyan** [iampopal/flutter_locales#9]
Hello! Can u help to understand. What am I doing wrong?

It's seems like unsoported pub lib   intl: ^0.18.1

Because no versions of flutter_locales match >3.0.1 <4.0.0 and flutter_locales 3.0.1 depends on flutter_localizations from sdk, flutter_locales ^3.0.1 requires flutter_localizations   
  from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, flutter_locales ^3.0.1 requires intl 0.18.0.

**Comment by iampopal** [comment]
There are 2 ways to fix this issue:

1) Update other of your packages to latest version so other packages will
also include intl: ^0.18.1

2) Downgrade flutter_locales: ^2.0.2

**Comment by iampopal** [comment]
New version of package has fixed this issue.
